on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to build spark-cdm
    steps:
    - name: Build spark-cdm step
      id: build-spark-cdm-workflow
      uses: Azure/spark-cdm@updaterelease
